// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServiceService_ServiceMemberByAccountID_FullMethodName             = "/cti.service.v1.ServiceService/ServiceMemberByAccountID"
	ServiceService_TeamIDByAccountID_FullMethodName                    = "/cti.service.v1.ServiceService/TeamIDByAccountID"
	ServiceService_ServicePackageAllByServiceCategoryID_FullMethodName = "/cti.service.v1.ServiceService/ServicePackageAllByServiceCategoryID"
)

// ServiceServiceClient is the client API for ServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceServiceClient interface {
	ServiceMemberByAccountID(ctx context.Context, in *ServiceMemberByAccountIDRequest, opts ...grpc.CallOption) (*ServiceMemberByAccountIDResponse, error)
	TeamIDByAccountID(ctx context.Context, in *TeamIDByAccountIDRequest, opts ...grpc.CallOption) (*TeamIDByAccountIDResponse, error)
	ServicePackageAllByServiceCategoryID(ctx context.Context, in *ServicePackageAllByServiceCategoryIDRequest, opts ...grpc.CallOption) (*ServicePackageAllByServiceCategoryIDResponse, error)
}

type serviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceServiceClient(cc grpc.ClientConnInterface) ServiceServiceClient {
	return &serviceServiceClient{cc}
}

func (c *serviceServiceClient) ServiceMemberByAccountID(ctx context.Context, in *ServiceMemberByAccountIDRequest, opts ...grpc.CallOption) (*ServiceMemberByAccountIDResponse, error) {
	out := new(ServiceMemberByAccountIDResponse)
	err := c.cc.Invoke(ctx, ServiceService_ServiceMemberByAccountID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) TeamIDByAccountID(ctx context.Context, in *TeamIDByAccountIDRequest, opts ...grpc.CallOption) (*TeamIDByAccountIDResponse, error) {
	out := new(TeamIDByAccountIDResponse)
	err := c.cc.Invoke(ctx, ServiceService_TeamIDByAccountID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceServiceClient) ServicePackageAllByServiceCategoryID(ctx context.Context, in *ServicePackageAllByServiceCategoryIDRequest, opts ...grpc.CallOption) (*ServicePackageAllByServiceCategoryIDResponse, error) {
	out := new(ServicePackageAllByServiceCategoryIDResponse)
	err := c.cc.Invoke(ctx, ServiceService_ServicePackageAllByServiceCategoryID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServiceServer is the server API for ServiceService service.
// All implementations must embed UnimplementedServiceServiceServer
// for forward compatibility
type ServiceServiceServer interface {
	ServiceMemberByAccountID(context.Context, *ServiceMemberByAccountIDRequest) (*ServiceMemberByAccountIDResponse, error)
	TeamIDByAccountID(context.Context, *TeamIDByAccountIDRequest) (*TeamIDByAccountIDResponse, error)
	ServicePackageAllByServiceCategoryID(context.Context, *ServicePackageAllByServiceCategoryIDRequest) (*ServicePackageAllByServiceCategoryIDResponse, error)
	mustEmbedUnimplementedServiceServiceServer()
}

// UnimplementedServiceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServiceServer struct {
}

func (UnimplementedServiceServiceServer) ServiceMemberByAccountID(context.Context, *ServiceMemberByAccountIDRequest) (*ServiceMemberByAccountIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceMemberByAccountID not implemented")
}
func (UnimplementedServiceServiceServer) TeamIDByAccountID(context.Context, *TeamIDByAccountIDRequest) (*TeamIDByAccountIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TeamIDByAccountID not implemented")
}
func (UnimplementedServiceServiceServer) ServicePackageAllByServiceCategoryID(context.Context, *ServicePackageAllByServiceCategoryIDRequest) (*ServicePackageAllByServiceCategoryIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServicePackageAllByServiceCategoryID not implemented")
}
func (UnimplementedServiceServiceServer) mustEmbedUnimplementedServiceServiceServer() {}

// UnsafeServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServiceServer will
// result in compilation errors.
type UnsafeServiceServiceServer interface {
	mustEmbedUnimplementedServiceServiceServer()
}

func RegisterServiceServiceServer(s grpc.ServiceRegistrar, srv ServiceServiceServer) {
	s.RegisterService(&ServiceService_ServiceDesc, srv)
}

func _ServiceService_ServiceMemberByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceMemberByAccountIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).ServiceMemberByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_ServiceMemberByAccountID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).ServiceMemberByAccountID(ctx, req.(*ServiceMemberByAccountIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_TeamIDByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamIDByAccountIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).TeamIDByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_TeamIDByAccountID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).TeamIDByAccountID(ctx, req.(*TeamIDByAccountIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceService_ServicePackageAllByServiceCategoryID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicePackageAllByServiceCategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServiceServer).ServicePackageAllByServiceCategoryID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceService_ServicePackageAllByServiceCategoryID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServiceServer).ServicePackageAllByServiceCategoryID(ctx, req.(*ServicePackageAllByServiceCategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceService_ServiceDesc is the grpc.ServiceDesc for ServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cti.service.v1.ServiceService",
	HandlerType: (*ServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceMemberByAccountID",
			Handler:    _ServiceService_ServiceMemberByAccountID_Handler,
		},
		{
			MethodName: "TeamIDByAccountID",
			Handler:    _ServiceService_TeamIDByAccountID_Handler,
		},
		{
			MethodName: "ServicePackageAllByServiceCategoryID",
			Handler:    _ServiceService_ServicePackageAllByServiceCategoryID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
