// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: role.proto

package role

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RoleService_AccountRoleAdd_FullMethodName        = "/cti.role.v1.RoleService/AccountRoleAdd"
	RoleService_AccountRoleCheckScope_FullMethodName = "/cti.role.v1.RoleService/AccountRoleCheckScope"
)

// RoleServiceClient is the client API for RoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleServiceClient interface {
	AccountRoleAdd(ctx context.Context, in *AccountRoleAddRequest, opts ...grpc.CallOption) (*AccountRoleAddResponse, error)
	AccountRoleCheckScope(ctx context.Context, in *AccountRoleCheckScopeRequest, opts ...grpc.CallOption) (*AccountRoleCheckScopeResponse, error)
}

type roleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleServiceClient(cc grpc.ClientConnInterface) RoleServiceClient {
	return &roleServiceClient{cc}
}

func (c *roleServiceClient) AccountRoleAdd(ctx context.Context, in *AccountRoleAddRequest, opts ...grpc.CallOption) (*AccountRoleAddResponse, error) {
	out := new(AccountRoleAddResponse)
	err := c.cc.Invoke(ctx, RoleService_AccountRoleAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleServiceClient) AccountRoleCheckScope(ctx context.Context, in *AccountRoleCheckScopeRequest, opts ...grpc.CallOption) (*AccountRoleCheckScopeResponse, error) {
	out := new(AccountRoleCheckScopeResponse)
	err := c.cc.Invoke(ctx, RoleService_AccountRoleCheckScope_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServiceServer is the server API for RoleService service.
// All implementations must embed UnimplementedRoleServiceServer
// for forward compatibility
type RoleServiceServer interface {
	AccountRoleAdd(context.Context, *AccountRoleAddRequest) (*AccountRoleAddResponse, error)
	AccountRoleCheckScope(context.Context, *AccountRoleCheckScopeRequest) (*AccountRoleCheckScopeResponse, error)
	mustEmbedUnimplementedRoleServiceServer()
}

// UnimplementedRoleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRoleServiceServer struct {
}

func (UnimplementedRoleServiceServer) AccountRoleAdd(context.Context, *AccountRoleAddRequest) (*AccountRoleAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountRoleAdd not implemented")
}
func (UnimplementedRoleServiceServer) AccountRoleCheckScope(context.Context, *AccountRoleCheckScopeRequest) (*AccountRoleCheckScopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountRoleCheckScope not implemented")
}
func (UnimplementedRoleServiceServer) mustEmbedUnimplementedRoleServiceServer() {}

// UnsafeRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleServiceServer will
// result in compilation errors.
type UnsafeRoleServiceServer interface {
	mustEmbedUnimplementedRoleServiceServer()
}

func RegisterRoleServiceServer(s grpc.ServiceRegistrar, srv RoleServiceServer) {
	s.RegisterService(&RoleService_ServiceDesc, srv)
}

func _RoleService_AccountRoleAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRoleAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).AccountRoleAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_AccountRoleAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).AccountRoleAdd(ctx, req.(*AccountRoleAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleService_AccountRoleCheckScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountRoleCheckScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServiceServer).AccountRoleCheckScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleService_AccountRoleCheckScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServiceServer).AccountRoleCheckScope(ctx, req.(*AccountRoleCheckScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleService_ServiceDesc is the grpc.ServiceDesc for RoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cti.role.v1.RoleService",
	HandlerType: (*RoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountRoleAdd",
			Handler:    _RoleService_AccountRoleAdd_Handler,
		},
		{
			MethodName: "AccountRoleCheckScope",
			Handler:    _RoleService_AccountRoleCheckScope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "role.proto",
}
