// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageService_MailAdminCreate_FullMethodName         = "/cti.message.v1.MessageService/MailAdminCreate"
	MessageService_MailUserCreate_FullMethodName          = "/cti.message.v1.MessageService/MailUserCreate"
	MessageService_NotificationUserCreate_FullMethodName  = "/cti.message.v1.MessageService/NotificationUserCreate"
	MessageService_NotificationAdminCreate_FullMethodName = "/cti.message.v1.MessageService/NotificationAdminCreate"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	MailAdminCreate(ctx context.Context, in *MailCreateRequest, opts ...grpc.CallOption) (*MailCreateResponse, error)
	MailUserCreate(ctx context.Context, in *MailCreateRequest, opts ...grpc.CallOption) (*MailCreateResponse, error)
	NotificationUserCreate(ctx context.Context, in *NotificationCreateRequest, opts ...grpc.CallOption) (*NotificationCreateResponse, error)
	NotificationAdminCreate(ctx context.Context, in *NotificationCreateRequest, opts ...grpc.CallOption) (*NotificationCreateResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) MailAdminCreate(ctx context.Context, in *MailCreateRequest, opts ...grpc.CallOption) (*MailCreateResponse, error) {
	out := new(MailCreateResponse)
	err := c.cc.Invoke(ctx, MessageService_MailAdminCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MailUserCreate(ctx context.Context, in *MailCreateRequest, opts ...grpc.CallOption) (*MailCreateResponse, error) {
	out := new(MailCreateResponse)
	err := c.cc.Invoke(ctx, MessageService_MailUserCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) NotificationUserCreate(ctx context.Context, in *NotificationCreateRequest, opts ...grpc.CallOption) (*NotificationCreateResponse, error) {
	out := new(NotificationCreateResponse)
	err := c.cc.Invoke(ctx, MessageService_NotificationUserCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) NotificationAdminCreate(ctx context.Context, in *NotificationCreateRequest, opts ...grpc.CallOption) (*NotificationCreateResponse, error) {
	out := new(NotificationCreateResponse)
	err := c.cc.Invoke(ctx, MessageService_NotificationAdminCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	MailAdminCreate(context.Context, *MailCreateRequest) (*MailCreateResponse, error)
	MailUserCreate(context.Context, *MailCreateRequest) (*MailCreateResponse, error)
	NotificationUserCreate(context.Context, *NotificationCreateRequest) (*NotificationCreateResponse, error)
	NotificationAdminCreate(context.Context, *NotificationCreateRequest) (*NotificationCreateResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
}

func (UnimplementedMessageServiceServer) MailAdminCreate(context.Context, *MailCreateRequest) (*MailCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MailAdminCreate not implemented")
}
func (UnimplementedMessageServiceServer) MailUserCreate(context.Context, *MailCreateRequest) (*MailCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MailUserCreate not implemented")
}
func (UnimplementedMessageServiceServer) NotificationUserCreate(context.Context, *NotificationCreateRequest) (*NotificationCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificationUserCreate not implemented")
}
func (UnimplementedMessageServiceServer) NotificationAdminCreate(context.Context, *NotificationCreateRequest) (*NotificationCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotificationAdminCreate not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_MailAdminCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MailAdminCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MailAdminCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MailAdminCreate(ctx, req.(*MailCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MailUserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MailCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MailUserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MailUserCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MailUserCreate(ctx, req.(*MailCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_NotificationUserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).NotificationUserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_NotificationUserCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).NotificationUserCreate(ctx, req.(*NotificationCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_NotificationAdminCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).NotificationAdminCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_NotificationAdminCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).NotificationAdminCreate(ctx, req.(*NotificationCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cti.message.v1.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MailAdminCreate",
			Handler:    _MessageService_MailAdminCreate_Handler,
		},
		{
			MethodName: "MailUserCreate",
			Handler:    _MessageService_MailUserCreate_Handler,
		},
		{
			MethodName: "NotificationUserCreate",
			Handler:    _MessageService_NotificationUserCreate_Handler,
		},
		{
			MethodName: "NotificationAdminCreate",
			Handler:    _MessageService_NotificationAdminCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
